server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://124.221.169.240:3306/student-management?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjl15977@163.com

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
