server:
  port: 9009
spring:
  datasource:
    url: jdbc:mysql://124.221.169.240:3306/student-management?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjl15977@163.com

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/generated/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    use-column-label: true
    use-generated-keys: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql